name: Build Docker Image

on:
    workflow_dispatch:

    push:
        # branches:
        #   - '**'

permissions:
    id-token: write
    contents: read

env:
    IMAGE_NAME: nodejs-docker-app

jobs:
    build:
        runs-on: ubuntu-latest
        environment: dev

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Azure Login via OIDC
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Verify Azure Login
              run: |
                  az account show

            - name: Debug Repository Structure
              run: |
                  pwd
                  find . -name Dockerfile

            - name: Build Docker Image
              run: |
                  docker build \
                    -f environments/Dockerfile \
                    -t $IMAGE_NAME:${{ github.sha }} \
                    environments

            - name: Show Docker Images
              run: |
                  docker images

# This workflow is for docker and we will be creating azure container registry to
# push the docker image to the acr
